#!/usr/bin/python3
# -*- coding: utf-8 -*-

edit_res_case = [
    ['00', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Once', 'Play', 'screen_test_numb'],
    ['01', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Daily', 'Play', 'screen_test_numb'],
    ['02', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Weekly', 'Play', 'screen_test_numb'],
    ['03', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Once', 'PVR', 'screen_test_numb'],
    ['04', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Daily', 'PVR', 'screen_test_numb'],
    ['05', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Weekly', 'PVR', 'screen_test_numb'],
    ['06', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Once', 'Power Off', 'screen_test_numb'],
    ['07', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Daily', 'Power Off', 'screen_test_numb'],
    ['08', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['09', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Once', 'Power On', 'screen_test_numb'],
    ['10', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Daily', 'Power On', 'screen_test_numb'],
    ['11', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Weekly', 'Power On', 'screen_test_numb'],
    ['12', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'PVR', 'screen_test_numb'],
    ['13', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'Power Off', 'screen_test_numb'],
    ['14', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'Power On', 'screen_test_numb'],
    ['15', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'Play', 'screen_test_numb'],
    ['16', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'Power Off', 'screen_test_numb'],
    ['17', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'Power On', 'screen_test_numb'],
    ['18', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'Play', 'screen_test_numb'],
    ['19', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'PVR', 'screen_test_numb'],
    ['20', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'Power On', 'screen_test_numb'],
    ['21', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'Play', 'screen_test_numb'],
    ['22', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'PVR', 'screen_test_numb'],
    ['23', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'Power Off', 'screen_test_numb'],
    ['24', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'PVR', 'screen_test_numb'],
    ['25', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'Power Off', 'screen_test_numb'],
    ['26', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'Power On', 'screen_test_numb'],
    ['27', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'Play', 'screen_test_numb'],
    ['28', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'Power Off', 'screen_test_numb'],
    ['29', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'Power On', 'screen_test_numb'],
    ['30', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'Play', 'screen_test_numb'],
    ['31', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'PVR', 'screen_test_numb'],
    ['32', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'Power On', 'screen_test_numb'],
    ['33', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'Play', 'screen_test_numb'],
    ['34', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'PVR', 'screen_test_numb'],
    ['35', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'Power Off', 'screen_test_numb'],
    ['36', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Weekly', 'PVR', 'screen_test_numb'],
    ['37', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['38', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Weekly', 'Power On', 'screen_test_numb'],
    ['39', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Weekly', 'Play', 'screen_test_numb'],
    ['40', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['41', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Weekly', 'Power On', 'screen_test_numb'],
    ['42', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Weekly', 'Play', 'screen_test_numb'],
    ['43', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Weekly', 'PVR', 'screen_test_numb'],
    ['44', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Weekly', 'Power On', 'screen_test_numb'],
    ['45', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Weekly', 'Play', 'screen_test_numb'],
    ['46', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Weekly', 'PVR', 'screen_test_numb'],
    ['47', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['48', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration', 'Once', 'PVR', 'screen_test_numb'],
    ['49', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration', 'Daily', 'PVR', 'screen_test_numb'],
    ['50', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration', 'Weekly', 'PVR', 'screen_test_numb'],
    ['51', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['52', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['53', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['54', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['55', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['56', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['57', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['58', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['59', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['60', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['61', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['62', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['63', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['64', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['65', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['66', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['67', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['68', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['69', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['70', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['71', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['72', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['73', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['74', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['75', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['76', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['77', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['78', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['79', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Once', 'PVR', 'screen_test_numb'],
    ['80', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Once', 'Power Off', 'screen_test_numb'],
    ['81', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Once', 'Power On', 'screen_test_numb'],
    ['82', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Once', 'Play', 'screen_test_numb'],
    ['83', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Once', 'Power Off', 'screen_test_numb'],
    ['84', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Once', 'Power On', 'screen_test_numb'],
    ['85', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Once', 'Play', 'screen_test_numb'],
    ['86', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Once', 'PVR', 'screen_test_numb'],
    ['87', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Once', 'Power On', 'screen_test_numb'],
    ['88', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Once', 'Play', 'screen_test_numb'],
    ['89', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Once', 'PVR', 'screen_test_numb'],
    ['90', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Once', 'Power Off', 'screen_test_numb'],
    ['91', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Daily', 'PVR', 'screen_test_numb'],
    ['92', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Daily', 'Power Off', 'screen_test_numb'],
    ['93', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Daily', 'Power On', 'screen_test_numb'],
    ['94', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Daily', 'Play', 'screen_test_numb'],
    ['95', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Daily', 'Power Off', 'screen_test_numb'],
    ['96', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Daily', 'Power On', 'screen_test_numb'],
    ['97', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Daily', 'Play', 'screen_test_numb'],
    ['98', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Daily', 'PVR', 'screen_test_numb'],
    ['99', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Daily', 'Power On', 'screen_test_numb'],
    ['100', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Daily', 'Play', 'screen_test_numb'],
    ['101', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Daily', 'PVR', 'screen_test_numb'],
    ['102', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Daily', 'Power Off', 'screen_test_numb'],
    ['103', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Weekly', 'PVR', 'screen_test_numb'],
    ['104', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['105', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Weekly', 'Power On', 'screen_test_numb'],
    ['106', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Weekly', 'Play', 'screen_test_numb'],
    ['107', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['108', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Weekly', 'Power On', 'screen_test_numb'],
    ['109', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Weekly', 'Play', 'screen_test_numb'],
    ['110', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Weekly', 'PVR', 'screen_test_numb'],
    ['111', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Weekly', 'Power On', 'screen_test_numb'],
    ['112', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Weekly', 'Play', 'screen_test_numb'],
    ['113', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Weekly', 'PVR', 'screen_test_numb'],
    ['114', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['115', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyDuration', 'Once', 'PVR', 'screen_test_numb'],
    ['116', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyDuration', 'Daily', 'PVR', 'screen_test_numb'],
    ['117', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyDuration', 'Weekly', 'PVR', 'screen_test_numb'],
    ['118', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['119', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['120', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['121', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['122', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['123', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['124', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['125', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['126', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['127', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['128', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['129', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['130', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['131', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['132', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['133', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['134', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['135', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['136', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['137', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['138', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['139', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['140', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['141', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['142', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['143', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['144', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['145', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['146', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration', 'Once', 'PVR', 'screen_test_numb'],
    ['147', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration', 'Daily', 'PVR', 'screen_test_numb'],
    ['148', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration', 'Weekly', 'PVR', 'screen_test_numb'],
    ['149', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration', 'Once', 'PVR', 'screen_test_numb'],
    ['150', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration', 'Daily', 'PVR', 'screen_test_numb'],
    ['151', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration', 'Weekly', 'PVR', 'screen_test_numb'],
    ['152', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration', 'Once', 'PVR', 'screen_test_numb'],
    ['153', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration', 'Daily', 'PVR', 'screen_test_numb'],
    ['154', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration', 'Weekly', 'PVR', 'screen_test_numb'],
    ['155', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['156', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['157', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['158', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['159', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['160', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['161', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['162', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['163', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['164', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['165', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['166', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['167', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['168', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['169', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['170', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['171', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['172', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['173', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['174', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['175', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['176', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['177', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['178', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['179', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['180', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['181', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['182', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['183', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['184', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['185', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['186', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['187', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['188', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['189', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['190', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['191', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['192', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['193', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['194', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['195', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['196', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['197', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['198', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['199', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['200', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['201', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['202', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['203', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['204', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['205', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['206', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['207', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['208', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['209', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['210', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['211', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['212', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['213', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['214', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['215', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['216', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['217', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['218', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['219', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['220', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['221', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['222', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['223', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['224', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['225', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['226', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['227', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['228', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['229', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['230', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['231', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['232', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['233', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['234', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['235', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['236', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['237', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['238', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['239', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['240', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['241', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['242', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['243', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['244', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['245', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['246', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration', 'Once', 'PVR', 'screen_test_numb'],
    ['247', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration', 'Daily', 'PVR', 'screen_test_numb'],
    ['248', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration', 'Weekly', 'PVR', 'screen_test_numb'],
    ['249', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration', 'Once', 'PVR', 'screen_test_numb'],
    ['250', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration', 'Daily', 'PVR', 'screen_test_numb'],
    ['251', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration', 'Weekly', 'PVR', 'screen_test_numb'],
    ['252', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration', 'Once', 'PVR', 'screen_test_numb'],
    ['253', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration', 'Daily', 'PVR', 'screen_test_numb'],
    ['254', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration', 'Weekly', 'PVR', 'screen_test_numb'],
    ['255', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['256', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['257', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['258', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['259', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['260', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['261', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['262', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['263', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['264', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['265', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['266', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['267', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['268', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['269', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['270', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['271', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['272', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['273', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['274', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['275', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['276', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['277', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['278', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['279', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['280', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['281', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['282', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['283', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['284', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['285', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['286', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['287', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['288', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['289', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['290', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['291', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['292', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['293', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['294', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['295', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['296', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['297', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['298', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['299', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['300', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['301', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['302', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['303', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['304', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['305', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['306', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['307', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['308', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['309', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['310', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['311', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['312', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['313', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['314', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['315', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Power On', 'screen_test_numb'],
    ['316', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Power On', 'screen_test_numb'],
    ['317', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power On', 'screen_test_numb'],
    ['318', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['319', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['320', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['321', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['322', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['323', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['324', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Play', 'screen_test_numb'],
    ['325', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['326', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['327', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['328', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['329', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['330', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['331', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['332', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['333', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['334', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['335', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['336', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['337', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['338', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyMode', 'Weekly', 'Power Off', 'screen_test_numb'],
    ['339', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['340', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['341', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['342', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['343', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['344', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['345', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['346', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['347', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['348', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['349', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['350', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['351', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['352', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['353', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['354', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['355', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['356', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['357', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['358', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['359', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['360', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['361', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['362', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['363', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['364', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['365', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['366', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['367', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['368', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['369', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['370', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['371', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['372', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['373', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['374', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['375', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['376', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['377', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
    ['378', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['379', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['380', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime+ModifyType+ModifyDuration+ModifyMode', 'Weekly', 'PVR', 'screen_test_numb'],
]

read_data = []

with open("add_and_edit_res_event_example_file.py", "r") as f:
    for line in f.readlines():
        print(line, end='')
        read_data.append(line)


def build_x_numb_python_file():
    for i in range(len(edit_res_case)):
        rename_modify_type = edit_res_case[i][7].replace('Modify', '')  # 用于提取TEST_CASE_INFO[7]中重复的Modify
        modify_name = f"Modify{rename_modify_type}"     # 不能加括号在py文件名称中，集合测试时不能执行
        if edit_res_case[i][4] == "Power Off" or edit_res_case[i][9] == "Power Off" \
                or edit_res_case[i][4] == "Power On" or edit_res_case[i][9] == "Power On":
            # 这里要注意py文件的名称不能有空格，会导致python3 xxx.py执行错误
            python_file_path = "Modify_{}_{}_{}_{}_{}_{}_{}.py".format(edit_res_case[i][0], edit_res_case[i][2],
                                                                       edit_res_case[i][3],
                                                                       edit_res_case[i][4].replace(" ", ''),
                                                                       modify_name, edit_res_case[i][8],
                                                                       edit_res_case[i][9].replace(" ", ''))
        else:
            python_file_path = "Modify_{}_{}_{}_{}_{}_{}_{}.py".format(edit_res_case[i][0], edit_res_case[i][2],
                                                                       edit_res_case[i][3], edit_res_case[i][4],
                                                                       modify_name, edit_res_case[i][8],
                                                                       edit_res_case[i][9])
        with open(python_file_path, "a+") as fo:
            for j in range(len(read_data)):
                if "choice_case_numb =" in read_data[j]:
                    fo.write("choice_case_numb = {}\n".format(int(edit_res_case[i][0])))
                elif "case_info" in read_data[j]:
                    fo.write(f"case_info = {edit_res_case[i]}\n")
                else:
                    fo.write(read_data[j])


build_x_numb_python_file()
