#!/usr/bin/python3
# -*- coding: utf-8 -*-

same_start_time_case = [
    ['00', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type+mode]', 'Once', 'Play',
     'screen_test_numb'],
    ['01', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type+mode]', 'Daily', 'Play',
     'screen_test_numb'],
    ['02', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type+mode]', 'Weekly', 'Play',
     'screen_test_numb'],
    ['03', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type+mode]', 'Once', 'PVR',
     'screen_test_numb'],
    ['04', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type+mode]', 'Daily', 'PVR',
     'screen_test_numb'],
    ['05', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type+mode]', 'Weekly', 'PVR',
     'screen_test_numb'],
    ['06', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type+mode]', 'Once',
     'Power Off', 'screen_test_numb'],
    ['07', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type+mode]', 'Daily',
     'Power Off', 'screen_test_numb'],
    ['08', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type+mode]', 'Weekly',
     'Power Off', 'screen_test_numb'],
    ['09', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type+mode]', 'Once', 'Power On',
     'screen_test_numb'],
    ['10', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type+mode]', 'Daily',
     'Power On', 'screen_test_numb'],
    ['11', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type+mode]', 'Weekly',
     'Power On', 'screen_test_numb'],
    ['12', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Once', 'PVR',
     'screen_test_numb'],
    ['13', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Once',
     'Power Off', 'screen_test_numb'],
    ['14', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Once',
     'Power On', 'screen_test_numb'],
    ['15', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Once', 'Play',
     'screen_test_numb'],
    ['16', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Once',
     'Power Off', 'screen_test_numb'],
    ['17', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Once',
     'Power On', 'screen_test_numb'],
    ['18', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Once',
     'Play', 'screen_test_numb'],
    ['19', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Once',
     'PVR', 'screen_test_numb'],
    ['20', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Once',
     'Power On', 'screen_test_numb'],
    ['21', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Once',
     'Play', 'screen_test_numb'],
    ['22', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Once',
     'PVR', 'screen_test_numb'],
    ['23', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Once',
     'Power Off', 'screen_test_numb'],
    ['24', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Daily', 'PVR',
     'screen_test_numb'],
    ['25', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Daily',
     'Power Off', 'screen_test_numb'],
    ['26', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Daily',
     'Power On', 'screen_test_numb'],
    ['27', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Daily', 'Play',
     'screen_test_numb'],
    ['28', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Daily',
     'Power Off', 'screen_test_numb'],
    ['29', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Daily',
     'Power On', 'screen_test_numb'],
    ['30', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Daily',
     'Play', 'screen_test_numb'],
    ['31', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Daily',
     'PVR', 'screen_test_numb'],
    ['32', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Daily',
     'Power On', 'screen_test_numb'],
    ['33', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Daily',
     'Play', 'screen_test_numb'],
    ['34', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Daily',
     'PVR', 'screen_test_numb'],
    ['35', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Daily',
     'Power Off', 'screen_test_numb'],
    ['36', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Weekly',
     'PVR', 'screen_test_numb'],
    ['37', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Weekly',
     'Power Off', 'screen_test_numb'],
    ['38', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Weekly',
     'Power On', 'screen_test_numb'],
    ['39', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Weekly',
     'Play', 'screen_test_numb'],
    ['40', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Weekly',
     'Power Off', 'screen_test_numb'],
    ['41', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Weekly',
     'Power On', 'screen_test_numb'],
    ['42', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Weekly',
     'Play', 'screen_test_numb'],
    ['43', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Weekly',
     'PVR', 'screen_test_numb'],
    ['44', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Weekly',
     'Power On', 'screen_test_numb'],
    ['45', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Weekly',
     'Play', 'screen_test_numb'],
    ['46', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Weekly',
     'PVR', 'screen_test_numb'],
    ['47', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+mode]+Diff[type]', 'Weekly',
     'Power Off', 'screen_test_numb'],
    ['48', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Daily', 'Play',
     'screen_test_numb'],
    ['49', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Weekly', 'Play',
     'screen_test_numb'],
    ['50', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Once', 'Play',
     'screen_test_numb'],
    ['51', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Weekly',
     'Play', 'screen_test_numb'],
    ['52', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Once', 'Play',
     'screen_test_numb'],
    ['53', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Daily',
     'Play', 'screen_test_numb'],
    ['54', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Daily', 'PVR',
     'screen_test_numb'],
    ['55', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Weekly', 'PVR',
     'screen_test_numb'],
    ['56', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Once', 'PVR',
     'screen_test_numb'],
    ['57', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Weekly', 'PVR',
     'screen_test_numb'],
    ['58', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Once', 'PVR',
     'screen_test_numb'],
    ['59', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Daily', 'PVR',
     'screen_test_numb'],
    ['60', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Daily',
     'Power Off', 'screen_test_numb'],
    ['61', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Weekly',
     'Power Off', 'screen_test_numb'],
    ['62', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Once',
     'Power Off', 'screen_test_numb'],
    ['63', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Weekly',
     'Power Off', 'screen_test_numb'],
    ['64', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Once',
     'Power Off', 'screen_test_numb'],
    ['65', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Daily',
     'Power Off', 'screen_test_numb'],
    ['66', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Daily',
     'Power On', 'screen_test_numb'],
    ['67', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Weekly',
     'Power On', 'screen_test_numb'],
    ['68', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Once',
     'Power On', 'screen_test_numb'],
    ['69', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Weekly',
     'Power On', 'screen_test_numb'],
    ['70', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Once',
     'Power On', 'screen_test_numb'],
    ['71', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time+type]+Diff[mode]', 'Daily',
     'Power On', 'screen_test_numb'],
    ['72', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily', 'PVR',
     'screen_test_numb'],
    ['73', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly', 'PVR',
     'screen_test_numb'],
    ['74', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once', 'PVR',
     'screen_test_numb'],
    ['75', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly', 'PVR',
     'screen_test_numb'],
    ['76', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once', 'PVR',
     'screen_test_numb'],
    ['77', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily', 'PVR',
     'screen_test_numb'],
    ['78', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Power Off', 'screen_test_numb'],
    ['79', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Power Off', 'screen_test_numb'],
    ['80', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Power Off', 'screen_test_numb'],
    ['81', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Power Off', 'screen_test_numb'],
    ['82', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Power Off', 'screen_test_numb'],
    ['83', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Power Off', 'screen_test_numb'],
    ['84', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Power On', 'screen_test_numb'],
    ['85', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Power On', 'screen_test_numb'],
    ['86', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Power On', 'screen_test_numb'],
    ['87', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Power On', 'screen_test_numb'],
    ['88', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Power On', 'screen_test_numb'],
    ['89', 'All', 'TV', 'Weekly', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Power On', 'screen_test_numb'],
    ['90', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily', 'Play',
     'screen_test_numb'],
    ['91', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly', 'Play',
     'screen_test_numb'],
    ['92', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once', 'Play',
     'screen_test_numb'],
    ['93', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly', 'Play',
     'screen_test_numb'],
    ['94', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once', 'Play',
     'screen_test_numb'],
    ['95', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily', 'Play',
     'screen_test_numb'],
    ['96', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Power Off', 'screen_test_numb'],
    ['97', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Power Off', 'screen_test_numb'],
    ['98', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Power Off', 'screen_test_numb'],
    ['99', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Power Off', 'screen_test_numb'],
    ['100', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Power Off', 'screen_test_numb'],
    ['101', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Power Off', 'screen_test_numb'],
    ['102', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Power On', 'screen_test_numb'],
    ['103', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Power On', 'screen_test_numb'],
    ['104', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Power On', 'screen_test_numb'],
    ['105', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Power On', 'screen_test_numb'],
    ['106', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Power On', 'screen_test_numb'],
    ['107', 'All', 'TV', 'Weekly', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Power On', 'screen_test_numb'],
    ['108', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Play', 'screen_test_numb'],
    ['109', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Play', 'screen_test_numb'],
    ['110', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Play', 'screen_test_numb'],
    ['111', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Play', 'screen_test_numb'],
    ['112', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Play', 'screen_test_numb'],
    ['113', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Play', 'screen_test_numb'],
    ['114', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'PVR', 'screen_test_numb'],
    ['115', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'PVR', 'screen_test_numb'],
    ['116', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'PVR', 'screen_test_numb'],
    ['117', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'PVR', 'screen_test_numb'],
    ['118', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'PVR', 'screen_test_numb'],
    ['119', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'PVR', 'screen_test_numb'],
    ['120', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Power On', 'screen_test_numb'],
    ['121', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Power On', 'screen_test_numb'],
    ['122', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Power On', 'screen_test_numb'],
    ['123', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Power On', 'screen_test_numb'],
    ['124', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Power On', 'screen_test_numb'],
    ['125', 'All', 'TV', 'Weekly', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Power On', 'screen_test_numb'],
    ['126', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Play', 'screen_test_numb'],
    ['127', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Play', 'screen_test_numb'],
    ['128', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Play', 'screen_test_numb'],
    ['129', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Play', 'screen_test_numb'],
    ['130', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Play', 'screen_test_numb'],
    ['131', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Play', 'screen_test_numb'],
    ['132', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'PVR', 'screen_test_numb'],
    ['133', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'PVR', 'screen_test_numb'],
    ['134', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'PVR', 'screen_test_numb'],
    ['135', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'PVR', 'screen_test_numb'],
    ['136', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'PVR', 'screen_test_numb'],
    ['137', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'PVR', 'screen_test_numb'],
    ['138', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Power Off', 'screen_test_numb'],
    ['139', 'All', 'TV', 'Once', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Power Off', 'screen_test_numb'],
    ['140', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Power Off', 'screen_test_numb'],
    ['141', 'All', 'TV', 'Daily', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Weekly',
     'Power Off', 'screen_test_numb'],
    ['142', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Once',
     'Power Off', 'screen_test_numb'],
    ['143', 'All', 'TV', 'Weekly', 'Power On', 'TVScreenDiffCH', 'Manual_jump', 'Same[time]+Diff[type+mode]', 'Daily',
     'Power Off', 'screen_test_numb']
]

read_data = []

with open("create_same_start_time_res_event_example_file.py", "r") as f:
    for line in f.readlines():
        print(line, end='')
        read_data.append(line)


def build_x_numb_python_file():
    for i in range(len(same_start_time_case)):
        # rename_modify_type = same_start_time_case[i][7].replace('Modify', '')  # 用于提取TEST_CASE_INFO[7]中重复的Modify
        # modify_name = f"Modify{rename_modify_type}"     # 不能加括号在py文件名称中，集合测试时不能执行
        if same_start_time_case[i][4] == "Power Off" or same_start_time_case[i][9] == "Power Off" \
                or same_start_time_case[i][4] == "Power On" or same_start_time_case[i][9] == "Power On":
            # 这里要注意py文件的名称不能有空格，会导致python3 xxx.py执行错误
            python_file_path = "Invalid_{}_{}_{}_{}_{}_{}_{}.py".format(same_start_time_case[i][0],
                                                                        same_start_time_case[i][2],
                                                                        same_start_time_case[i][3],
                                                                        same_start_time_case[i][4].replace(" ", ''),
                                                                        same_start_time_case[i][7],
                                                                        same_start_time_case[i][8],
                                                                        same_start_time_case[i][9].replace(" ", ''))
        else:
            python_file_path = "Invalid_{}_{}_{}_{}_{}_{}_{}.py".format(same_start_time_case[i][0],
                                                                        same_start_time_case[i][2],
                                                                        same_start_time_case[i][3],
                                                                        same_start_time_case[i][4],
                                                                        same_start_time_case[i][7],
                                                                        same_start_time_case[i][8],
                                                                        same_start_time_case[i][9])
        with open(python_file_path, "a+") as fo:
            for j in range(len(read_data)):
                if "choice_case_numb =" in read_data[j]:
                    fo.write("choice_case_numb = {}\n".format(int(same_start_time_case[i][0])))
                elif "case_info" in read_data[j]:
                    fo.write(f"case_info = {same_start_time_case[i]}\n")
                else:
                    fo.write(read_data[j])


build_x_numb_python_file()
