#!/usr/bin/python3
# -*- coding: utf-8 -*-

import serial
import serial.tools.list_ports
import platform
import logging

ser_cable_num = 7


def check_ports():
    send_com, receive_com = '', ''
    send_port_desc, receive_port_desc = '', ''
    ports_info = []
    if platform.system() == "Windows":
        serial_ser = {
            "1": "FTDVKA2HA",
            "2": "FTGDWJ64A",
            "3": "FT9SP964A",
            "4": "FTHB6SSTA",
            "5": "FTDVKPRSA",
            "6": "FTHI8UIHA",
            "7": "FTHG05TTA",
        }
        send_port_desc = "USB-SERIAL CH340"
        # receive_port_desc = serial_ser[str(ser_cable_num)]
        receive_port_desc = "FT232R USB UART"
    elif platform.system() == "Linux":
        serial_ser = {
            "1": "FTDVKA2H",
            "2": "FTGDWJ64",
            "3": "FT9SP964",
            "4": "FTHB6SST",
            "5": "FTDVKPRS",
            "6": "FTHI8UIH",
            "7": "FTHG05TT",
        }
        send_port_desc = "USB2.0-Serial"
        # receive_port_desc = serial_ser[str(ser_cable_num)]
        receive_port_desc = "FT232R USB UART"
    ports = list(serial.tools.list_ports.comports())
    for i in range(len(ports)):
        logging.info("可用端口:名称:{} + 描述:{} + 硬件id:{}".format(ports[i].device, ports[i].description, ports[i].hwid))
        # print("可用端口:名称:{} + 描述:{} + 硬件id:{}".format(ports[i].device, ports[i].description, ports[i].hwid))
        ports_info.append("{}~{}~{}".format(ports[i].device, ports[i].description, ports[i].hwid))
    if len(ports) <= 0:
        logging.info("无可用端口")
    elif len(ports) == 1:
        logging.info("只有一个可用端口:{}".format(ports[0].device))
    elif len(ports) >= 2:
        for i in range(len(ports_info)):
            if send_port_desc in ports_info[i]:
                send_com = ports_info[i].split("~")[0]
            elif receive_port_desc in ports_info[i]:
                receive_com = ports_info[i].split("~")[0]
    return send_com, receive_com


# KEY = {
#         "POWER": "A1 F1 22 DD 0A", "TV/R": "A1 F1 22 DD 42", "MUTE": "A1 F1 22 DD 10",
#         "1": "A1 F1 22 DD 01", "2": "A1 F1 22 DD 02", "3": "A1 F1 22 DD 03",
#         "4": "A1 F1 22 DD 04", "5": "A1 F1 22 DD 05", "6": "A1 F1 22 DD 06",
#         "7": "A1 F1 22 DD 07", "8": "A1 F1 22 DD 08", "9": "A1 F1 22 DD 09",
#         "FAV": "A1 F1 22 DD 1E", "0": "A1 F1 22 DD 00", "SAT": "A1 F1 22 DD 16",
#         "MENU": "A1 F1 22 DD 0C", "EPG": "A1 F1 22 DD 0E", "INFO": "A1 F1 22 DD 1F", "EXIT": "A1 F1 22 DD 0D",
#         "UP": "A1 F1 22 DD 11", "DOWN": "A1 F1 22 DD 14",
#         "LEFT": "A1 F1 22 DD 12", "RIGHT": "A1 F1 22 DD 13", "OK": "A1 F1 22 DD 15",
#         "P/N": "A1 F1 22 DD 0F", "SLEEP": "A1 F1 22 DD 17", "PAGE_UP": "A1 F1 22 DD 41", "PAGE_DOWN": "A1 F1 22 DD 18",
#         "RED": "A1 F1 22 DD 19", "GREEN": "A1 F1 22 DD 1A", "YELLOW": "A1 F1 22 DD 1B", "BLUE": "A1 F1 22 DD 1C",
#         "F1": "A1 F1 22 DD 46", "F2": "A1 F1 22 DD 45", "F3": "A1 F1 22 DD 44", "RECALL": "A1 F1 22 DD 43",
#         "REWIND": "A1 F1 22 DD 1D", "FF": "A1 F1 22 DD 47", "PLAY": "A1 F1 22 DD 0B", "RECORD": "A1 F1 22 DD 40",
#         "PREVIOUS": "A1 F1 22 DD 4A", "NEXT": "A1 F1 22 DD 49", "TIMESHIFT": "A1 F1 22 DD 48", "STOP": "A1 F1 22 DD 4D",
#     }
# REVERSE_KEY = dict([val, key] for key, val in KEY.items())
#
# rsv_key = {
#         "POWER": "0xbbaf", "TV/R": "0xbbbd", "MUTE": "0xbbf7",
#         "1": "0xbb7f", "2": "0xbbbf", "3": "0xbb3f",
#         "4": "0xbbdf", "5": "0xbb5f", "6": "0xbb9f",
#         "7": "0xbb1f", "8": "0xbbef", "9": "0xbb6f",
#         "FAV": "0xbb87", "0": "0xbbff", "SAT": "0xbb97",
#         "MENU": "0xbbcf", "EPG": "0xbb8f", "INFO": "0xbb07", "EXIT": "0xbb4f",
#         "UP": "0xbb77", "DOWN": "0xbbd7",
#         "LEFT": "0xbbb7", "RIGHT": "0xbb37", "OK": "0xbb57",
#         "P/N": "0xbb0f", "SLEEP": "0xbb17", "PAGE_UP": "0xbb7d", "PAGE_DOWN": "0xbbe7",
#         "RED": "0xbb67", "GREEN": "0xbba7", "YELLOW": "0xbb27", "BLUE": "0xbbc7",
#         "F1": "0xbb9d", "F2": "0xbb5d", "F3": "0xbbdd", "RECALL": "0xbb3d",
#         "REWIND": "0xbb47", "FF": "0xbb1d", "PLAY": "0xbb2f", "RECORD": "0xbbfd",
#         "PREVIOUS": "0xbbad", "NEXT": "0xbb6d", "TIMESHIFT": "0xbbed", "STOP": "0xbb4d"
#     }
# reverse_rsv_key = dict([val, key] for key, val in rsv_key.items())

new_add_res_case = [
    ['00', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['01', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['02', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['03', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['04', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['05', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['06', 'All', 'TV', 'Mon.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['07', 'All', 'TV', 'Mon.', 'Play', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['08', 'All', 'TV', 'Mon.', 'Play', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['09', 'All', 'TV', 'Tues.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['10', 'All', 'TV', 'Tues.', 'Play', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['11', 'All', 'TV', 'Tues.', 'Play', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['12', 'All', 'TV', 'Wed.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['13', 'All', 'TV', 'Wed.', 'Play', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['14', 'All', 'TV', 'Wed.', 'Play', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['15', 'All', 'TV', 'Thurs.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['16', 'All', 'TV', 'Thurs.', 'Play', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['17', 'All', 'TV', 'Thurs.', 'Play', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['18', 'All', 'TV', 'Fri.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['19', 'All', 'TV', 'Fri.', 'Play', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['20', 'All', 'TV', 'Fri.', 'Play', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['21', 'All', 'TV', 'Sat.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['22', 'All', 'TV', 'Sat.', 'Play', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['23', 'All', 'TV', 'Sat.', 'Play', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['24', 'All', 'TV', 'Sun.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['25', 'All', 'TV', 'Sun.', 'Play', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['26', 'All', 'TV', 'Sun.', 'Play', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['27', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['28', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['29', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['30', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['31', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['32', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['33', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['34', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['35', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['36', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['37', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['38', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['39', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['40', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['41', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['42', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['43', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['44', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['45', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['46', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['47', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['48', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['49', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['50', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['51', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['52', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['53', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['54', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['55', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['56', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['57', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['58', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['59', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['60', 'All', 'TV', 'Mon.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['61', 'All', 'TV', 'Mon.', 'Power Off', 'TVScreenDiffCH', 'Auto_jump', 'screen_test_numb'],
    ['62', 'All', 'TV', 'Mon.', 'Power Off', 'TVScreenDiffCH', 'Cancel_jump', 'screen_test_numb'],
    ['63', 'All', 'Radio', 'Once', 'PVR', 'RadioScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['64', 'All', 'TV', 'Once', 'PVR', 'RadioScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['65', 'All', 'TV', 'Daily', 'PVR', 'RadioScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['66', 'All', 'TV', 'Mon.', 'PVR', 'RadioScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['67', 'All', 'TV', 'Tues.', 'PVR', 'RadioScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['68', 'All', 'TV', 'Wed.', 'PVR', 'RadioScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['69', 'All', 'TV', 'Thurs.', 'PVR', 'RadioScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['70', 'All', 'TV', 'Fri.', 'PVR', 'RadioScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['71', 'All', 'TV', 'Sat.', 'PVR', 'RadioScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['72', 'All', 'TV', 'Sun.', 'PVR', 'RadioScreenDiffCH', 'Manual_jump', 'screen_test_numb'],
    ['73', 'All', 'TV', 'Daily', 'Play', 'ChannelList', 'Manual_jump', 'other_interface_test_numb'],
    ['74', 'All', 'TV', 'Mon.', 'Play', 'Menu', 'Manual_jump', 'other_interface_test_numb'],
    ['75', 'All', 'TV', 'Fri.', 'Play', 'EPG', 'Manual_jump', 'other_interface_test_numb'],
    ['76', 'All', 'TV', 'Once', 'Play', 'ChannelEdit', 'Manual_jump', 'other_interface_test_numb']
]

epg_basic_case = [
    ["00", "GX", "TV", "EPG+Exit", "EnterExitEPGInterface"],
    ["01", "GX", "Radio", "EPG+Exit", "EnterExitEPGInterface"],
    ["02", "GX", "TV", "UP", "EPGSwitchChannel"],
    ["03", "GX", "TV", "DOWN", "EPGSwitchChannel"],
    ["04", "GX", "TV", "UP+Random", "EPGSwitchChannel"],
    ["05", "GX", "TV", "DOWN+Random", "EPGSwitchChannel"],
    ["06", "GX", "TV", "UP+DOWN+Random", "EPGSwitchChannel"],
    ["07", "GX", "Radio", "UP", "EPGSwitchChannel"],
    ["08", "GX", "Radio", "DOWN", "EPGSwitchChannel"],
    ["09", "GX", "Radio", "UP+Random", "EPGSwitchChannel"],
    ["10", "GX", "Radio", "DOWN+Random", "EPGSwitchChannel"],
    ["11", "GX", "Radio", "UP+DOWN+Random", "EPGSwitchChannel"],
    ["12", "GX", "TV", "LEFT", "SwitchEPGEvent"],
    ["13", "GX", "TV", "RIGHT", "SwitchEPGEvent"],
    ["14", "GX", "TV", "LEFT+Random", "SwitchEPGEvent"],
    ["15", "GX", "TV", "RIGHT+Random", "SwitchEPGEvent"],
    ["16", "GX", "TV", "RIGHT+LEFT+Random", "SwitchEPGEvent"],
    ["17", "GX", "TV", "Day+", "SwitchEPGEvent"],
    ["18", "GX", "TV", "Day-", "SwitchEPGEvent"],
    ["19", "GX", "TV", "Day++RIGHT+Random", "SwitchEPGEvent"],
    ["20", "GX", "TV", "Day++LEFT+Random", "SwitchEPGEvent"],
    ["21", "GX", "TV", "Day++LEFTorRIGHT+Random", "SwitchEPGEvent"],
    ["22", "GX", "TV", "Day-+RIGHT+Random", "SwitchEPGEvent"],
    ["23", "GX", "TV", "Day-+LEFT+Random", "SwitchEPGEvent"],
    ["24", "GX", "TV", "Day-+LEFTorRIGHT+Random", "SwitchEPGEvent"],
    ["25", "GX", "TV", "Day+orDay-orLEFTorRIGHT+Random", "SwitchEPGEvent"],
    ["26", "GX", "Radio", "LEFT", "SwitchEPGEvent"],
    ["27", "GX", "Radio", "RIGHT", "SwitchEPGEvent"],
    ["28", "GX", "Radio", "LEFT+Random", "SwitchEPGEvent"],
    ["29", "GX", "Radio", "RIGHT+Random", "SwitchEPGEvent"],
    ["30", "GX", "Radio", "RIGHT+LEFT+Random", "SwitchEPGEvent"],
    ["31", "GX", "Radio", "Day+", "SwitchEPGEvent"],
    ["32", "GX", "Radio", "Day-", "SwitchEPGEvent"],
    ["33", "GX", "Radio", "Day++RIGHT+Random", "SwitchEPGEvent"],
    ["34", "GX", "Radio", "Day++LEFT+Random", "SwitchEPGEvent"],
    ["35", "GX", "Radio", "Day++LEFTorRIGHT+Random", "SwitchEPGEvent"],
    ["36", "GX", "Radio", "Day-+RIGHT+Random", "SwitchEPGEvent"],
    ["37", "GX", "Radio", "Day-+LEFT+Random", "SwitchEPGEvent"],
    ["38", "GX", "Radio", "Day-+LEFTorRIGHT+Random", "SwitchEPGEvent"],
    ["39", "GX", "Radio", "Day+orDay-orLEFTorRIGHT+Random", "SwitchEPGEvent"],
    ["40", "GX", "TV", "LEFT+OK", "SwitchAndDetailEPGEvent"],
    ["41", "GX", "TV", "RIGHT+OK", "SwitchAndDetailEPGEvent"],
    ["42", "GX", "TV", "LEFT+Random+OK", "SwitchAndDetailEPGEvent"],
    ["43", "GX", "TV", "RIGHT+Random+OK", "SwitchAndDetailEPGEvent"],
    ["44", "GX", "Radio", "LEFT+OK", "SwitchAndDetailEPGEvent"],
    ["45", "GX", "Radio", "RIGHT+OK", "SwitchAndDetailEPGEvent"],
    ["46", "GX", "Radio", "LEFT+Random+OK", "SwitchAndDetailEPGEvent"],
    ["47", "GX", "Radio", "RIGHT+Random+OK", "SwitchAndDetailEPGEvent"]
]

edit_res_case = [
    ['00', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Once', 'Play', 'screen_test_numb'],
    ['01', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Daily', 'Play', 'screen_test_numb'],
    ['02', 'All', 'TV', 'Mon.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Mon.', 'Play', 'screen_test_numb'],
    ['03', 'All', 'TV', 'Tues.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Tues.', 'Play', 'screen_test_numb'],
    ['04', 'All', 'TV', 'Wed.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Wed.', 'Play', 'screen_test_numb'],
    ['05', 'All', 'TV', 'Thurs.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Thurs.', 'Play', 'screen_test_numb'],
    ['06', 'All', 'TV', 'Fri.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Fri.', 'Play', 'screen_test_numb'],
    ['07', 'All', 'TV', 'Sat.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Sat.', 'Play', 'screen_test_numb'],
    ['08', 'All', 'TV', 'Sun.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Sun.', 'Play', 'screen_test_numb'],
    ['09', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Once', 'PVR', 'screen_test_numb'],
    ['10', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Daily', 'PVR', 'screen_test_numb'],
    ['11', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Mon.', 'PVR', 'screen_test_numb'],
    ['12', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Tues.', 'PVR', 'screen_test_numb'],
    ['13', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Wed.', 'PVR', 'screen_test_numb'],
    ['14', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Thurs.', 'PVR', 'screen_test_numb'],
    ['15', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Fri.', 'PVR', 'screen_test_numb'],
    ['16', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Sat.', 'PVR', 'screen_test_numb'],
    ['17', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Sun.', 'PVR', 'screen_test_numb'],
    ['18', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Once', 'Power Off', 'screen_test_numb'],
    ['19', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Daily', 'Power Off', 'screen_test_numb'],
    ['20', 'All', 'TV', 'Mon.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Mon.', 'Power Off', 'screen_test_numb'],
    ['21', 'All', 'TV', 'Tues.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Tues.', 'Power Off', 'screen_test_numb'],
    ['22', 'All', 'TV', 'Wed.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Wed.', 'Power Off', 'screen_test_numb'],
    ['23', 'All', 'TV', 'Thurs.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Thurs.', 'Power Off', 'screen_test_numb'],
    ['24', 'All', 'TV', 'Fri.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Fri.', 'Power Off', 'screen_test_numb'],
    ['25', 'All', 'TV', 'Sat.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Sat.', 'Power Off', 'screen_test_numb'],
    ['26', 'All', 'TV', 'Sun.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyTime', 'Sun.', 'Power Off', 'screen_test_numb'],
    ['27', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'PVR', 'screen_test_numb'],
    ['28', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'Power Off', 'screen_test_numb'],
    ['29', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'Play', 'screen_test_numb'],
    ['30', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'Power Off', 'screen_test_numb'],
    ['31', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'Play', 'screen_test_numb'],
    ['32', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Once', 'PVR', 'screen_test_numb'],
    ['33', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'PVR', 'screen_test_numb'],
    ['34', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'Power Off', 'screen_test_numb'],
    ['35', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'Play', 'screen_test_numb'],
    ['36', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'Power Off', 'screen_test_numb'],
    ['37', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'Play', 'screen_test_numb'],
    ['38', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Daily', 'PVR', 'screen_test_numb'],
    ['39', 'All', 'TV', 'Mon.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Mon.', 'PVR', 'screen_test_numb'],
    ['40', 'All', 'TV', 'Mon.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Mon.', 'Power Off', 'screen_test_numb'],
    ['41', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Mon.', 'Play', 'screen_test_numb'],
    ['42', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Mon.', 'Power Off', 'screen_test_numb'],
    ['43', 'All', 'TV', 'Mon.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Mon.', 'Play', 'screen_test_numb'],
    ['44', 'All', 'TV', 'Mon.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Mon.', 'PVR', 'screen_test_numb'],
    ['45', 'All', 'TV', 'Tues.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Tues.', 'PVR', 'screen_test_numb'],
    ['46', 'All', 'TV', 'Tues.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Tues.', 'Power Off', 'screen_test_numb'],
    ['47', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Tues.', 'Play', 'screen_test_numb'],
    ['48', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Tues.', 'Power Off', 'screen_test_numb'],
    ['49', 'All', 'TV', 'Tues.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Tues.', 'Play', 'screen_test_numb'],
    ['50', 'All', 'TV', 'Tues.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Tues.', 'PVR', 'screen_test_numb'],
    ['51', 'All', 'TV', 'Wed.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Wed.', 'PVR', 'screen_test_numb'],
    ['52', 'All', 'TV', 'Wed.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Wed.', 'Power Off', 'screen_test_numb'],
    ['53', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Wed.', 'Play', 'screen_test_numb'],
    ['54', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Wed.', 'Power Off', 'screen_test_numb'],
    ['55', 'All', 'TV', 'Wed.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Wed.', 'Play', 'screen_test_numb'],
    ['56', 'All', 'TV', 'Wed.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Wed.', 'PVR', 'screen_test_numb'],
    ['57', 'All', 'TV', 'Thurs.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Thurs.', 'PVR', 'screen_test_numb'],
    ['58', 'All', 'TV', 'Thurs.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Thurs.', 'Power Off', 'screen_test_numb'],
    ['59', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Thurs.', 'Play', 'screen_test_numb'],
    ['60', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Thurs.', 'Power Off', 'screen_test_numb'],
    ['61', 'All', 'TV', 'Thurs.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Thurs.', 'Play', 'screen_test_numb'],
    ['62', 'All', 'TV', 'Thurs.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Thurs.', 'PVR', 'screen_test_numb'],
    ['63', 'All', 'TV', 'Fri.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Fri.', 'PVR', 'screen_test_numb'],
    ['64', 'All', 'TV', 'Fri.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Fri.', 'Power Off', 'screen_test_numb'],
    ['65', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Fri.', 'Play', 'screen_test_numb'],
    ['66', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Fri.', 'Power Off', 'screen_test_numb'],
    ['67', 'All', 'TV', 'Fri.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Fri.', 'Play', 'screen_test_numb'],
    ['68', 'All', 'TV', 'Fri.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Fri.', 'PVR', 'screen_test_numb'],
    ['69', 'All', 'TV', 'Sat.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Sat.', 'PVR', 'screen_test_numb'],
    ['70', 'All', 'TV', 'Sat.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Sat.', 'Power Off', 'screen_test_numb'],
    ['71', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Sat.', 'Play', 'screen_test_numb'],
    ['72', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Sat.', 'Power Off', 'screen_test_numb'],
    ['73', 'All', 'TV', 'Sat.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Sat.', 'Play', 'screen_test_numb'],
    ['74', 'All', 'TV', 'Sat.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Sat.', 'PVR', 'screen_test_numb'],
    ['75', 'All', 'TV', 'Sun.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Sun.', 'PVR', 'screen_test_numb'],
    ['76', 'All', 'TV', 'Sun.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Sun.', 'Power Off', 'screen_test_numb'],
    ['77', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Sun.', 'Play', 'screen_test_numb'],
    ['78', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Sun.', 'Power Off', 'screen_test_numb'],
    ['79', 'All', 'TV', 'Sun.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Sun.', 'Play', 'screen_test_numb'],
    ['80', 'All', 'TV', 'Sun.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyType', 'Sun.', 'PVR', 'screen_test_numb'],
    ['81', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration', 'Once', 'PVR', 'screen_test_numb'],
    ['82', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration', 'Daily', 'PVR', 'screen_test_numb'],
    ['83', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration', 'Mon.', 'PVR', 'screen_test_numb'],
    ['84', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration', 'Tues.', 'PVR', 'screen_test_numb'],
    ['85', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration', 'Wed.', 'PVR', 'screen_test_numb'],
    ['86', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration', 'Thurs.', 'PVR', 'screen_test_numb'],
    ['87', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration', 'Fri.', 'PVR', 'screen_test_numb'],
    ['88', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration', 'Sat.', 'PVR', 'screen_test_numb'],
    ['89', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyDuration', 'Sun.', 'PVR', 'screen_test_numb'],
    ['90', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['91', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Play', 'screen_test_numb'],
    ['92', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Play', 'screen_test_numb'],
    ['93', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Play', 'screen_test_numb'],
    ['94', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Play', 'screen_test_numb'],
    ['95', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Play', 'screen_test_numb'],
    ['96', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Play', 'screen_test_numb'],
    ['97', 'All', 'TV', 'Once', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Play', 'screen_test_numb'],
    ['98', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['99', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Play', 'screen_test_numb'],
    ['100', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Play', 'screen_test_numb'],
    ['101', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Play', 'screen_test_numb'],
    ['102', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Play', 'screen_test_numb'],
    ['103', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Play', 'screen_test_numb'],
    ['104', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Play', 'screen_test_numb'],
    ['105', 'All', 'TV', 'Daily', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Play', 'screen_test_numb'],
    ['106', 'All', 'TV', 'Mon.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['107', 'All', 'TV', 'Mon.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['108', 'All', 'TV', 'Mon.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Play', 'screen_test_numb'],
    ['109', 'All', 'TV', 'Mon.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Play', 'screen_test_numb'],
    ['110', 'All', 'TV', 'Mon.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Play', 'screen_test_numb'],
    ['111', 'All', 'TV', 'Mon.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Play', 'screen_test_numb'],
    ['112', 'All', 'TV', 'Mon.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Play', 'screen_test_numb'],
    ['113', 'All', 'TV', 'Mon.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Play', 'screen_test_numb'],
    ['114', 'All', 'TV', 'Tues.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['115', 'All', 'TV', 'Tues.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['116', 'All', 'TV', 'Tues.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Play', 'screen_test_numb'],
    ['117', 'All', 'TV', 'Tues.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Play', 'screen_test_numb'],
    ['118', 'All', 'TV', 'Tues.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Play', 'screen_test_numb'],
    ['119', 'All', 'TV', 'Tues.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Play', 'screen_test_numb'],
    ['120', 'All', 'TV', 'Tues.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Play', 'screen_test_numb'],
    ['121', 'All', 'TV', 'Tues.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Play', 'screen_test_numb'],
    ['122', 'All', 'TV', 'Wed.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['123', 'All', 'TV', 'Wed.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['124', 'All', 'TV', 'Wed.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Play', 'screen_test_numb'],
    ['125', 'All', 'TV', 'Wed.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Play', 'screen_test_numb'],
    ['126', 'All', 'TV', 'Wed.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Play', 'screen_test_numb'],
    ['127', 'All', 'TV', 'Wed.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Play', 'screen_test_numb'],
    ['128', 'All', 'TV', 'Wed.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Play', 'screen_test_numb'],
    ['129', 'All', 'TV', 'Wed.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Play', 'screen_test_numb'],
    ['130', 'All', 'TV', 'Thurs.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['131', 'All', 'TV', 'Thurs.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['132', 'All', 'TV', 'Thurs.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Play', 'screen_test_numb'],
    ['133', 'All', 'TV', 'Thurs.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Play', 'screen_test_numb'],
    ['134', 'All', 'TV', 'Thurs.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Play', 'screen_test_numb'],
    ['135', 'All', 'TV', 'Thurs.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Play', 'screen_test_numb'],
    ['136', 'All', 'TV', 'Thurs.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Play', 'screen_test_numb'],
    ['137', 'All', 'TV', 'Thurs.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Play', 'screen_test_numb'],
    ['138', 'All', 'TV', 'Fri.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['139', 'All', 'TV', 'Fri.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['140', 'All', 'TV', 'Fri.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Play', 'screen_test_numb'],
    ['141', 'All', 'TV', 'Fri.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Play', 'screen_test_numb'],
    ['142', 'All', 'TV', 'Fri.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Play', 'screen_test_numb'],
    ['143', 'All', 'TV', 'Fri.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Play', 'screen_test_numb'],
    ['144', 'All', 'TV', 'Fri.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Play', 'screen_test_numb'],
    ['145', 'All', 'TV', 'Fri.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Play', 'screen_test_numb'],
    ['146', 'All', 'TV', 'Sat.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['147', 'All', 'TV', 'Sat.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['148', 'All', 'TV', 'Sat.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Play', 'screen_test_numb'],
    ['149', 'All', 'TV', 'Sat.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Play', 'screen_test_numb'],
    ['150', 'All', 'TV', 'Sat.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Play', 'screen_test_numb'],
    ['151', 'All', 'TV', 'Sat.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Play', 'screen_test_numb'],
    ['152', 'All', 'TV', 'Sat.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Play', 'screen_test_numb'],
    ['153', 'All', 'TV', 'Sat.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Play', 'screen_test_numb'],
    ['154', 'All', 'TV', 'Sun.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Play', 'screen_test_numb'],
    ['155', 'All', 'TV', 'Sun.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Play', 'screen_test_numb'],
    ['156', 'All', 'TV', 'Sun.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Play', 'screen_test_numb'],
    ['157', 'All', 'TV', 'Sun.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Play', 'screen_test_numb'],
    ['158', 'All', 'TV', 'Sun.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Play', 'screen_test_numb'],
    ['159', 'All', 'TV', 'Sun.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Play', 'screen_test_numb'],
    ['160', 'All', 'TV', 'Sun.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Play', 'screen_test_numb'],
    ['161', 'All', 'TV', 'Sun.', 'Play', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Play', 'screen_test_numb'],
    ['162', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['163', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'PVR', 'screen_test_numb'],
    ['164', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'PVR', 'screen_test_numb'],
    ['165', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'PVR', 'screen_test_numb'],
    ['166', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'PVR', 'screen_test_numb'],
    ['167', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'PVR', 'screen_test_numb'],
    ['168', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'PVR', 'screen_test_numb'],
    ['169', 'All', 'TV', 'Once', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'PVR', 'screen_test_numb'],
    ['170', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['171', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'PVR', 'screen_test_numb'],
    ['172', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'PVR', 'screen_test_numb'],
    ['173', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'PVR', 'screen_test_numb'],
    ['174', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'PVR', 'screen_test_numb'],
    ['175', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'PVR', 'screen_test_numb'],
    ['176', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'PVR', 'screen_test_numb'],
    ['177', 'All', 'TV', 'Daily', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'PVR', 'screen_test_numb'],
    ['178', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['179', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['180', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'PVR', 'screen_test_numb'],
    ['181', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'PVR', 'screen_test_numb'],
    ['182', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'PVR', 'screen_test_numb'],
    ['183', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'PVR', 'screen_test_numb'],
    ['184', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'PVR', 'screen_test_numb'],
    ['185', 'All', 'TV', 'Mon.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'PVR', 'screen_test_numb'],
    ['186', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['187', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['188', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'PVR', 'screen_test_numb'],
    ['189', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'PVR', 'screen_test_numb'],
    ['190', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'PVR', 'screen_test_numb'],
    ['191', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'PVR', 'screen_test_numb'],
    ['192', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'PVR', 'screen_test_numb'],
    ['193', 'All', 'TV', 'Tues.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'PVR', 'screen_test_numb'],
    ['194', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['195', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['196', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'PVR', 'screen_test_numb'],
    ['197', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'PVR', 'screen_test_numb'],
    ['198', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'PVR', 'screen_test_numb'],
    ['199', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'PVR', 'screen_test_numb'],
    ['200', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'PVR', 'screen_test_numb'],
    ['201', 'All', 'TV', 'Wed.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'PVR', 'screen_test_numb'],
    ['202', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['203', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['204', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'PVR', 'screen_test_numb'],
    ['205', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'PVR', 'screen_test_numb'],
    ['206', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'PVR', 'screen_test_numb'],
    ['207', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'PVR', 'screen_test_numb'],
    ['208', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'PVR', 'screen_test_numb'],
    ['209', 'All', 'TV', 'Thurs.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'PVR', 'screen_test_numb'],
    ['210', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['211', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['212', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'PVR', 'screen_test_numb'],
    ['213', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'PVR', 'screen_test_numb'],
    ['214', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'PVR', 'screen_test_numb'],
    ['215', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'PVR', 'screen_test_numb'],
    ['216', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'PVR', 'screen_test_numb'],
    ['217', 'All', 'TV', 'Fri.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'PVR', 'screen_test_numb'],
    ['218', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['219', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['220', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'PVR', 'screen_test_numb'],
    ['221', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'PVR', 'screen_test_numb'],
    ['222', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'PVR', 'screen_test_numb'],
    ['223', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'PVR', 'screen_test_numb'],
    ['224', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'PVR', 'screen_test_numb'],
    ['225', 'All', 'TV', 'Sat.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'PVR', 'screen_test_numb'],
    ['226', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'PVR', 'screen_test_numb'],
    ['227', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'PVR', 'screen_test_numb'],
    ['228', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'PVR', 'screen_test_numb'],
    ['229', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'PVR', 'screen_test_numb'],
    ['230', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'PVR', 'screen_test_numb'],
    ['231', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'PVR', 'screen_test_numb'],
    ['232', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'PVR', 'screen_test_numb'],
    ['233', 'All', 'TV', 'Sun.', 'PVR', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'PVR', 'screen_test_numb'],
    ['234', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['235', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Power Off', 'screen_test_numb'],
    ['236', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Power Off', 'screen_test_numb'],
    ['237', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Power Off', 'screen_test_numb'],
    ['238', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Power Off', 'screen_test_numb'],
    ['239', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Power Off', 'screen_test_numb'],
    ['240', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Power Off', 'screen_test_numb'],
    ['241', 'All', 'TV', 'Once', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Power Off', 'screen_test_numb'],
    ['242', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['243', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Power Off', 'screen_test_numb'],
    ['244', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Power Off', 'screen_test_numb'],
    ['245', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Power Off', 'screen_test_numb'],
    ['246', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Power Off', 'screen_test_numb'],
    ['247', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Power Off', 'screen_test_numb'],
    ['248', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Power Off', 'screen_test_numb'],
    ['249', 'All', 'TV', 'Daily', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Power Off', 'screen_test_numb'],
    ['250', 'All', 'TV', 'Mon.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['251', 'All', 'TV', 'Mon.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['252', 'All', 'TV', 'Mon.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Power Off', 'screen_test_numb'],
    ['253', 'All', 'TV', 'Mon.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Power Off', 'screen_test_numb'],
    ['254', 'All', 'TV', 'Mon.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Power Off', 'screen_test_numb'],
    ['255', 'All', 'TV', 'Mon.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Power Off', 'screen_test_numb'],
    ['256', 'All', 'TV', 'Mon.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Power Off', 'screen_test_numb'],
    ['257', 'All', 'TV', 'Mon.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Power Off', 'screen_test_numb'],
    ['258', 'All', 'TV', 'Tues.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['259', 'All', 'TV', 'Tues.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['260', 'All', 'TV', 'Tues.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Power Off', 'screen_test_numb'],
    ['261', 'All', 'TV', 'Tues.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Power Off', 'screen_test_numb'],
    ['262', 'All', 'TV', 'Tues.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Power Off', 'screen_test_numb'],
    ['263', 'All', 'TV', 'Tues.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Power Off', 'screen_test_numb'],
    ['264', 'All', 'TV', 'Tues.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Power Off', 'screen_test_numb'],
    ['265', 'All', 'TV', 'Tues.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Power Off', 'screen_test_numb'],
    ['266', 'All', 'TV', 'Wed.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['267', 'All', 'TV', 'Wed.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['268', 'All', 'TV', 'Wed.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Power Off', 'screen_test_numb'],
    ['269', 'All', 'TV', 'Wed.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Power Off', 'screen_test_numb'],
    ['270', 'All', 'TV', 'Wed.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Power Off', 'screen_test_numb'],
    ['271', 'All', 'TV', 'Wed.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Power Off', 'screen_test_numb'],
    ['272', 'All', 'TV', 'Wed.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Power Off', 'screen_test_numb'],
    ['273', 'All', 'TV', 'Wed.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Power Off', 'screen_test_numb'],
    ['274', 'All', 'TV', 'Thurs.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['275', 'All', 'TV', 'Thurs.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['276', 'All', 'TV', 'Thurs.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Power Off', 'screen_test_numb'],
    ['277', 'All', 'TV', 'Thurs.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Power Off', 'screen_test_numb'],
    ['278', 'All', 'TV', 'Thurs.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Power Off', 'screen_test_numb'],
    ['279', 'All', 'TV', 'Thurs.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Power Off', 'screen_test_numb'],
    ['280', 'All', 'TV', 'Thurs.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Power Off', 'screen_test_numb'],
    ['281', 'All', 'TV', 'Thurs.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Power Off', 'screen_test_numb'],
    ['282', 'All', 'TV', 'Fri.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['283', 'All', 'TV', 'Fri.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['284', 'All', 'TV', 'Fri.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Power Off', 'screen_test_numb'],
    ['285', 'All', 'TV', 'Fri.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Power Off', 'screen_test_numb'],
    ['286', 'All', 'TV', 'Fri.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Power Off', 'screen_test_numb'],
    ['287', 'All', 'TV', 'Fri.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Power Off', 'screen_test_numb'],
    ['288', 'All', 'TV', 'Fri.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Power Off', 'screen_test_numb'],
    ['289', 'All', 'TV', 'Fri.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Power Off', 'screen_test_numb'],
    ['290', 'All', 'TV', 'Sat.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['291', 'All', 'TV', 'Sat.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['292', 'All', 'TV', 'Sat.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Power Off', 'screen_test_numb'],
    ['293', 'All', 'TV', 'Sat.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Power Off', 'screen_test_numb'],
    ['294', 'All', 'TV', 'Sat.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Power Off', 'screen_test_numb'],
    ['295', 'All', 'TV', 'Sat.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Power Off', 'screen_test_numb'],
    ['296', 'All', 'TV', 'Sat.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Power Off', 'screen_test_numb'],
    ['297', 'All', 'TV', 'Sat.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sun.', 'Power Off', 'screen_test_numb'],
    ['298', 'All', 'TV', 'Sun.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Once', 'Power Off', 'screen_test_numb'],
    ['299', 'All', 'TV', 'Sun.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Daily', 'Power Off', 'screen_test_numb'],
    ['300', 'All', 'TV', 'Sun.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Mon.', 'Power Off', 'screen_test_numb'],
    ['301', 'All', 'TV', 'Sun.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Tues.', 'Power Off', 'screen_test_numb'],
    ['302', 'All', 'TV', 'Sun.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Wed.', 'Power Off', 'screen_test_numb'],
    ['303', 'All', 'TV', 'Sun.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Thurs.', 'Power Off', 'screen_test_numb'],
    ['304', 'All', 'TV', 'Sun.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Fri.', 'Power Off', 'screen_test_numb'],
    ['305', 'All', 'TV', 'Sun.', 'Power Off', 'TVScreenDiffCH', 'Manual_jump', 'ModifyMode', 'Sat.', 'Power Off', 'screen_test_numb'],
]
